export const mokeChats = [
  {
    id: 1,
    img: `${import.meta.env.BASE_URL}assets/chat-avatar.png`,
    chatName: "BitConvex 1",
    chatRole: "Support Admin",
    date: "28 Dec",
    isOnline: true,
    description: "Hey Cak, Could you free now? Can you look and read the brief first…",
  },
  {
    id: 2,
    img: `${import.meta.env.BASE_URL}assets/chat-avatar.png`,
    chatName: "BitConvex long name",
    chatRole: "Support Admin long role",
    date: "28 Dec",
    isOnline: false,
    description: "Hey Cak, Could you free now? Can you look and read the brief first… long description wwwwwwwwwwwwwwwwwwwwwww",
  },
  {
    id: 3,
    img: `${import.meta.env.BASE_URL}assets/chat-avatar.png`,
    chatName: "BitConvex 3",
    chatRole: "Support Admin",
    date: "28 Dec",
    isOnline: true,
    description: "Hey Cak, Could you free now? Can you look and read the brief first…",
  },
  {
    id: 4,
    img: `${import.meta.env.BASE_URL}assets/chat-avatar.png`,
    chatName: "BitConvex 4",
    chatRole: "Support Admin",
    date: "28 Dec",
    isOnline: false,
    description: "Hey Cak, Could you free now? Can you look and read the brief first…",
  },
  {
    id: 5,
    img: `${import.meta.env.BASE_URL}assets/chat-avatar.png`,
    chatName: "BitConvex 5",
    chatRole: "Support Admin",
    date: "28 Dec",
    isOnline: true,
    description: "Hey Cak, Could you free now? Can you look and read the brief first…",
  },
  {
    id: 6,
    img: `${import.meta.env.BASE_URL}assets/chat-avatar.png`,
    chatName: "BitConvex 6",
    chatRole: "Support Admin",
    date: "28 Dec",
    isOnline: true,
    description: "Hey Cak, Could you free now? Can you look and read the brief first…",
  },
];
